Created a chat app and added a chat model
akshgpt7/summer-code-jam-2020 pull request #10
Opened 2020-08-03 17:21 UTC by kunalrustagi08

2020-08-03 22:05 UTC, akshgpt7 requested changes
There are a few unwanted fields in this model. Please remove them.
Also, please create a separate url and a view to handle the chat features, test it locally (by making a simple html template for testing) and see if you can make it work.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +    subject = models.CharField(_("Subject"), max_length=120, blank=True)
I don't think we need to translate the messages, like if you send a message in chat, it's sent as it is. So I think you should remove the translations.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +    subject = models.CharField(_("Subject"), max_length=120, blank=True)
I  don't understand the need of a `subject` for a chat if it's between 2 users. You can remove this attribute.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +                                  related_name='receiver_messages', null=True,
There _has_ to be a receiver to a message. So I think you shouldn't leave `null=True` and `blank=True`.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +    parent_msg = models.ForeignKey('self', related_name='next_messages',
I don't understand what this field is for when we already have the body field.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
I don't think for 'early internet', there was a feature of seeing when the message was read. I think you can remove this too.

2020-08-03 22:05 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +    recipient_deleted_at = models.DateTimeField(_("Recipient deleted at"),
I don't know what the `sender_deleted_at` and `recipient_deleted_at` are for. I think it just adds a little unwanted complexity.

2020-08-03 23:47 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/models.py
> +class Chat(models.Model):
I think you should just name this model `message`, since this stores the messages and will create a DB table for messages.

2020-08-06 02:04 UTC, akshgpt7 requested changes
Good work. This is coming along well. Just make the few changes, and learn how to use class based views. CBVs might seem overwhelming in the beginning, but once you understand them, they're much easier to use.
**Please add type hints wherever possible and docstrings for every view. Also, add comments in your code to explain the functioning (There are points for these things).**

Before pushing, test your changes by making a few message objects from the admin page and see if they're displaying correctly in the url.

2020-08-06 02:04 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/urls.py
> +    path('', views.chat, name="message")
Change the name of the url to `message-box`.

2020-08-06 02:04 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/views.py
> +def chat(request):
For this, there's a built in Django `ListView`. It's a class based view and does most of the work internally. Please use the built-in view. Make sure to add the condition to filter the queryset where receiver is only the currently logged in user.
Also, add the LoginRequired mixin to make sure only the logged in user can access their message box.

2020-08-06 02:04 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/chat/views.py
> +    messages_object = Message.objects.all()
You do not have to display all the messages from the db. Just add a filter like `Message.objects.filter(recipient=request.user)` (This is not the exact code, just the logic behind what you've to do). It'll be implemented a bit differently in class based view.

2020-08-06 02:04 UTC, akshgpt7 commented on annoyed-alligators/socl_media/urls.py
> +    path('message-box/', include('socl_media.apps.chat.urls'))
Don't `include` the `chat.urls` here. You can just directly call the view here itself since there's only one url for this app.

2020-08-06 16:26 UTC, kunalrustagi08 commented
@akshgpt7 added CBV for messages and recipient field for model. I did add some docstrings but couldnt find where to use typehints. will google more and add it later.

2020-08-07 03:21 UTC, merged

2020-08-07 03:22 UTC, akshgpt7 commented
Looks good! Thnaks.