Added password recovery feature
akshgpt7/summer-code-jam-2020 pull request #13
Opened 2020-08-05 15:33 UTC by nishithshowri006

2020-08-05 15:39 UTC, nishithshowri006 commented
@akshgpt7 I didn't add any mail features. When the password reset link will be appeared with metadata in a folder called sent_emails

2020-08-06 02:22 UTC, akshgpt7 commented
Great work, just add the change password functionality as well and then I'll merge it!
About the email, I asked the mods and they suggest to use a spare email. I've asked in our team channel.

2020-08-06 04:35 UTC, nishithshowri006 commented
@akshgpt7 added the functionality and it is working but I didn't add any html

2020-08-06 05:09 UTC, akshgpt7 requested changes

2020-08-06 05:09 UTC, akshgpt7 commented on annoyed-alligators/socl_media/urls.py
> +    path('password_reset_complete',
Don't add underscores in url path. Change these to hyphens as in other paths.

2020-08-06 05:11 UTC, akshgpt7 commented
Awesome! Just one thing: **Please add type hints wherever possible and docstrings for every view. Also, add comments in your code to explain the functioning (There are points for these things).**

2020-08-06 09:44 UTC, akshgpt7 requested changes

2020-08-06 09:44 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/feed/models.py
> +
Add docstrings for models as well, telling what they store.

2020-08-06 09:44 UTC, akshgpt7 commented on annoyed-alligators/socl_media/apps/feed/views.py
>  def feed(request):
For this, there's a built in Django ListView. It's a class based view and does most of the work internally. Please use the built-in view. 
Here's how to use them: https://youtu.be/Xeh9r0CXBmU

2020-08-06 09:45 UTC, akshgpt7 commented
Also, can you add the email part?

2020-08-06 11:55 UTC, nishithshowri006 commented
I actually added email part but the link at present is redirected into txt file in our project folder. We need to use some third party tools for sending email to user

2020-08-07 02:48 UTC, merged